version: '3.8'
services:
  webapp:
    image: node_app
    build: .
    container_name: node-app
    ports:
      - '8080:8080'
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    container_name: mongo-db
    ports:
      - '27017:27017'